default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: 
  socket: tmp/mysqld.sock

development:
  adapter: mysql2
  username: root
  password:
  host: localhost
  <<: *default
  database: protospace_40571_development # ファイル名

test:
  <<: *default
  database: protospace_40571_testc # ファイル名
  adapter: mysql2
  username: root
  password:
  host: localhost

production:
  <<: *default
  adapter: postgresql
  url: <%= ENV['DATABASE_URL'] %>        # Renderで使用する環境変数
